name: Build And Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs: 
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      
      - name: Install dependencies
        run: dotnet restore
        
      - name: Initialize Testing Stack
        run: docker-compose up -d db; \
./wait-for-it.sh localhost:5432 --timeout=5 --strict -- docker-compose up -d gotrue
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore
